name: GodCommand
version: 1.0.0
api: 5.0.0
main: WildanDev\GodCommand
author: WildanDev
description: Make player immune to all damage
commands:
  god:
    description: Allow player to use god command
    permission: god.use
    
permissions:
  god.use:
    description: Allow player using god command
    default: op
  
